name: Terraform Validate & Plan (Terraform Cloud)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Terraform Init
        working-directory: TF
        run: terraform init

      - name: Terraform Validate
        working-directory: TF
        run: terraform validate

      - name: Terraform Plan
        working-directory: TF
        run: terraform plan

      - name: Terraform Apply
        working-directory: TF
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
