name: Deploy website to AWS S3

on:
  push:
    branches:
      - main

jobs:
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Terraform Cloud
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.tfc_team_token }}"
              }
            }
          }
          EOF
        shell: bash

      - name: Terraform Init
        run: |
          cd TF
          terraform init

      - name: Terraform Validate
        run: |
          cd TF
          terraform validate

      - name: Terraform Plan
        run: |
          cd TF
          terraform plan

      - name: Terraform Apply via Cloud API
        run: |
          # Create a run in Terraform Cloud
          curl --location --request POST 'https://app.terraform.io/api/v2/runs' \
            --header 'Authorization: Bearer ${{ secrets.tfc_team_token }}' \
            --header 'Content-Type: application/vnd.api+json' \
            --data-raw '{
              "data": {
                "attributes": {
                  "auto-apply": true,
                  "message": "Auto-apply triggered by GitHub Actions"
                },
                "type": "runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "ws-library-analytics-tf"
                    }
                  }
                }
              }
            }'
        shell: bash
        env:
          TF_CLOUD_ORGANIZATION: TuwaAnalytics
          TF_WORKSPACE: library-analytics-tf

